### ISSUE TITLE
recursive relationship definition

### ISSUE THREAD

**Issue by freedafeng** [pythological/kanren#23]
trying to follow the examples in the readme to create an "ancestor" relation as follows,
 def ancestor(x, z): 
     y = var() 
     return lany(parent(x, z), lall(parent(y, z), ancestor(x, y))) 

Apparently sth is wrong, since I got the following error,
RecursionError: maximum recursion depth exceeded while calling a Python object
is recursion supported at all?

Thanks.

**Comment by brandonwillard** [comment]
Yes, recursion is definitely supported!  

For your situation, the easiest fix is to change `ancestor(x, y)` to `Zzz(ancestor, x, y)`.  

The helper goal `Zzz` can be imported from `kanren.core`, and its purpose is to create a goal that will delay evaluation of the recursive call until it actually needs to be evaluated.

For non-trivial examples of recursion, see the goals in `kanren.graph`.
