### ISSUE TITLE
How to define a recursive relation?

### ISSUE THREAD

**Issue by sebdumancic** [pythological/kanren#30]
Hi Brandon,

first of all, thank you for picking up this project. I'm very glad that someone is continuing the efforts made in logpy.

I'm having trouble specifying the recursive relations in miniKanren. For instance, I'm trying to specify a recursive `ancestor` relation and the following code
```
from kanren import Relation, facts, run, var, conde

parent = Relation()
facts(parent, ("Homer", "Bart"),
                       ("Homer", "Lisa"),
                       ("Abe", "Homer"))

x = var()
y = var()

def ancestor(x,y):
    z = var()
    return conde(parent(x,y), (parent(x, z), ancestor(z, y)))

print(run(1, [x, y], ancestor(x, y)))
```
ends up with the following error: `RecursionError: maximum recursion depth exceeded while calling a Python object`.
It seems that miniKanren just keeps adding recursive goals.

What is the correct way to specify recursive relation?

UPDATE:
I have managed to get a single answer by imitating the `membero` definition:
```
    def ancestor(x, z):

        def ancestor_goal(S):
            nonlocal x, z

            x_rf, ls_rf = reify((x, z), S)
            y = var()
            g = lany(parent(x, z), (parent(x, y), ancestor(y, z)))

            yield from g(S)

        return ancestor_goal
```
but this only works for `run(1,...)` and throws an error for everything else. ould be very interested in knowing how to write a general recursive method.

**Comment by brandonwillard** [comment]
The easiest way to define a recursive relation is with the goal [`Zzz`](https://github.com/pythological/kanren/blob/master/kanren/core.py#L164) (see https://github.com/pythological/kanren/issues/23#issuecomment-582199695 and the examples there).

For low-level goals, see the advice [here](https://github.com/pythological/kanren/issues/10#issue-541940424).

**Comment by brandonwillard** [comment]
Also, the `conde` form should contain another set of brackets/parentheses (i.e. each argument to `conde` is a list of goals):
```python
    return conde([parent(x,y)], [parent(x, z), ancestor(z, y)])
```

**Comment by sebdumancic** [comment]
Fantastic, this works! Thanks a lot. I was looking for some kind of a delayed execution but could not find it.
I will take it upon myself to make a PR with this example added, if you would see it fit.

Thanks for the tip for conde as well.

**Comment by brandonwillard** [comment]
Any time!  There's a lot going on in this project, so feel free to ask questions about anything.

**Comment by askr3d** [comment]
I'm new to this and I have the same error "maximun recursion depth exceeded while calling a Python object" I don't what to do
`from kanren import *

parent = Relation()

facts(
    parent, ("nathan", "steve"),
    ("nathan", "edith"),
    ("david", "john"),
    ("jim", "david"),
    ("steve", "jim"),
    ("david", "adrian"),
    ("jim", "homero"),
    ("homero", "bart"),
    ("homero", "lisa"),
    ("homero", "magie"),
    ("homero", "magie"),
    ("edith", "ramon"),
    ("edith", "felipe")
)

def ancestor(A, B):
    X = var()
    conde(parent(A, X), (parent(A, X), ancestor(X,B)))
    
Y = var()
print(run(4, Y, ancestor(Y, "john")))`

**Comment by brandonwillard** [comment]
> I'm new to this and I have the same error "maximun recursion depth exceeded while calling a Python object" I don't know what to do `from kanren import *
> 
> parent = Relation()
> 
> facts( parent, ("nathan", "steve"), ("nathan", "edith"), ("david", "john"), ("jim", "david"), ("steve", "jim"), ("david", "adrian"), ("jim", "homero"), ("homero", "bart"), ("homero", "lisa"), ("homero", "magie"), ("homero", "magie"), ("edith", "ramon"), ("edith", "felipe") )
> 
> def ancestor(A, B): X = var() conde(parent(A, X), (parent(A, X), ancestor(X,B)))
> 
> Y = var() print(run(4, Y, ancestor(Y, "john")))`

You might need to use the `Zzz` function [mentioned earlier in this issue](https://github.com/pythological/kanren/issues/30#issuecomment-605104063) to avoid infinite recursion (e.g. `Zzz(ancestor, X, B)` instead of `ancestor(X, B)`).

**Comment by askr3d** [comment]
> > I'm new to this and I have the same error "maximun recursion depth exceeded while calling a Python object" I don't know what to do `from kanren import *
> > parent = Relation()
> > facts( parent, ("nathan", "steve"), ("nathan", "edith"), ("david", "john"), ("jim", "david"), ("steve", "jim"), ("david", "adrian"), ("jim", "homero"), ("homero", "bart"), ("homero", "lisa"), ("homero", "magie"), ("homero", "magie"), ("edith", "ramon"), ("edith", "felipe") )
> > def ancestor(A, B): X = var() conde(parent(A, X), (parent(A, X), ancestor(X,B)))
> > Y = var() print(run(4, Y, ancestor(Y, "john")))`
> 
> You might need to use the `Zzz` function [mentioned earlier in this issue](https://github.com/pythological/kanren/issues/30#issuecomment-605104063) to avoid infinite recursion (e.g. `Zzz(ancestor, X, B)` instead of `ancestor(X, B)`).

I tried to use `Zzz` function but the problem still remain, All I did was run pip install miniKanren. I don't know if I should install another package
P.S. I made another function version but i don't think it is good practice
```
def ancestor(A, B):
    X = var()
    if run(1, A, grandparent(A,B)):
        return parent(A,X)
    elif run(1, A, parent(A,B)):
        return parent(A,B)
    else:
        return conde((parent(A,X), ancestor(X,B)))
```

**Comment by brandonwillard** [comment]
This should work:
```python
from kanren import *
from kanren.core import Zzz

parent = Relation()

facts(
    parent,
    ("nathan", "steve"),
    ("nathan", "edith"),
    ("david", "john"),
    ("jim", "david"),
    ("steve", "jim"),
    ("david", "adrian"),
    ("jim", "homero"),
    ("homero", "bart"),
    ("homero", "lisa"),
    ("homero", "magie"),
    ("homero", "magie"),
    ("edith", "ramon"),
    ("edith", "felipe"),
)


def ancestor(A, B):
    X = var()
    return conde([parent(A, B)], [parent(A, X), Zzz(ancestor, X, B)])


Y = var()
print(run(4, Y, ancestor(Y, "john")))
# ('david', 'steve', 'nathan', 'jim')
```

**Comment by askr3d** [comment]
Thank you so much, it works
