### ISSUE TITLE
Account example doesn't run

### ISSUE THREAD

**Issue by ryanprior** [pythological/kanren#35]
Hi there! The accounts example (in `examples/user_classes.py`) doesn't run. Instead I get this output:

```sh-session
$ python examples/user_classes.py 
Traceback (most recent call last):
  File "examples/user_classes.py", line 33, in <module>
    add(10, balance, newbalance),
TypeError: add expected 2 arguments, got 3
```

I notice that this example is also present in logpy: https://github.com/logpy/logpy/blob/master/examples/user_classes.py
But there it uses the `kanren.arith` module, which is absent in this repo.

I tried changing the example code to use `applyo` but this doesn't work either:
```python
theorist_bonus = lall(
    membero(source, accounts),
    membero(first, theorists),
    applyo(add, (10, balance), newbalance),
)
```

Is this example intended to run?

**Comment by brandonwillard** [comment]
Thanks for reporting that bug!

Yes, I believe `applyo` is a good replacement.  I've set up a fix using that approach in #36.
