### ISSUE TITLE
Ref your paper

### ISSUE THREAD

**Issue by majidaldo** [pythological/kanren#38]
I've been hovering  around your library  for a while. Funnily,  I only got to reading  your paper recently.  I think you should promote it in the Readme. 

It helps to understand it and its context. This is pretty  advanced stuff that even mathematically trained programmers are not aware of.

**Comment by majidaldo** [comment]
On that note maybe enable a discussion  section.

**Comment by brandonwillard** [comment]
Are you referring to ["miniKanren as a Tool for Symbolic Computation in Python"](https://arxiv.org/abs/2005.11644)?  If so, yes, I can add it to the README.

**Comment by majidaldo** [comment]
> Are you referring to ["miniKanren as a Tool for Symbolic Computation in Python"](https://arxiv.org/abs/2005.11644)? If so, yes, I can add it to the README.

Right.
