### ISSUE TITLE
(Q) Python 3.10 pattern  matching 

### ISSUE THREAD

**Issue by majidaldo** [pythological/kanren#41]
Just a question (hence the discussion section idea). With python 310 able to match even on types and undefined variables,  how much of the machinery developed here (or would that be in the unification and multiple dispatch library) can now be deferred to the python implementation?

**Comment by brandonwillard** [comment]
> how much of the machinery developed here (or would that be in the unification and multiple dispatch library) can now be deferred to the python implementation?

None of it.  It's possible that some code could be refactored to use it, but, from what I recall, Python's new pattern matching isn't a nearly flexible enough form of unification to obviate the need for `logical-unification`.
