### ISSUE TITLE
Add Mypy typing

### ISSUE THREAD

**Issue by brandonwillard** [pythological/kanren#49]
This project needs type annotations and a Mypy `pre-commit` hook.

**Comment by majidaldo** [comment]
just throwing the idea here to just generate the types from running the tests.

(/mypy/ typing? or just typing?)

**Comment by brandonwillard** [comment]
> just throwing the idea here to just generate the types from running the tests.
> 
> (/mypy/ typing? or just typing?)

This issue is for Mypy (i.e. checked typing), as well as the manual addition of type hints.  This codebase is small enough for that to be done manually.

**Comment by majidaldo** [comment]
can be closed (initially) with https://github.com/pythological/kanren/commit/7f9accbd7b31f7367bb5d0541397a3ce2dde4b8d#diff-789a9a451148e9f433bf6f9884fb3eb71cf80e3b44df048d464f081b53eb95a4

but the typing work could be more comprehensive.
